export * from './lib/entity.module'
export * from './lib/entity.service'
export * from './lib/i.entity'
export * from './lib/base.detail.component'
export * from './lib/base.edit.component'
export * from './lib/base.list.component'
