# 
# https://docs.docker.com/develop/develop-images/multistage-build/
# 
FROM my-base-image:nx-base AS base-image

ARG NODE_ENV
ARG BUILD_FLAG

WORKDIR /app/builder
RUN npx nx build auth-api ${BUILD_FLAG}

# 
# Start a new empty layer and copy only the requires folders onto it. 
#
# FROM node:16-alpine
# node:latest has bash installed, so you can run the container and open a shell on it.
FROM node:latest

WORKDIR /app/builder/dist
COPY --from=base-image /app/builder/dist/apps/auth-api .
# COPY --from=base-image /app/builder/node_modules ./node_modules
# WORKDIR ./dist
RUN npm install

# Expose is NOT supported by Heroku
# EXPOSE 3000
# EXPOSE 3306

ENV NODE_ENV=${NODE_ENV}

# Run the image as a non-root user
RUN adduser myuser
USER myuser

# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku			
# CMD node ./dist/apps/auth-api/main.js
CMD node ./main.js